const fs = require('fs');
const faker = require ('faker');
var rating = ['G','PG','PG-13','R']
var fakeData =[];
function recursionfunc(count){
  fakeData = [];
  if(count === 5) {
    return;
  }

  for(let i = 0; i < 10000; i++){
    fakeData.push(
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },{
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },{
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },{
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },{
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },{
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },{
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },{
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },{
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },{
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      },
      {
        name: faker.random.words(3),
        description: faker.lorem.paragraph(),
        genre: faker.hacker.adjective(),
        score: faker.random.number({min:1, max:10}),
        runtime: faker.random.number({min:100, max:150}),
        image: 'https://picsum.photos/200/300',
        rating: rating[faker.random.number({min:0, max:3})],
        releaseMonth:faker.date.month(),
        releaseDay:faker.random.number({min:1, max:30}),
        releaseYear:faker.random.number({min:1980, max:2018})
      }
    )
  }

  var fakeDataString= JSON.stringify(fakeData)

  fs.readFile(`./fakedata.json`,(err, data)=> {
    if(err) {
      fs.writeFile(`./fakedata.json`, fakeDataString, (err)=> {
        if(err) {
          console.log(err)
        }
        console.log('File Created')
        recursionfunc(count+1)
      });
    }else{
      var newData = fakeData.concat(JSON.parse(data));
      fs.writeFile('./fakedata.json', JSON.stringify(newData), (err)=> {
        if(err) {
          console.log(err);
        }
        console.log('File Updated', count)
        recursionfunc(count+1)
      });
    }
  });
  return;
}

recursionfunc(0);